version:
    "3.1"
networks:
    my-net:
services:
  http_server:
    build: ./http_server
    container_name: http_server
    restart: always
    networks:
      - my-net  
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    networks:
      - my-net
    ports:
      - 10086:3000

  mysql:
    image: mysql
    container_name: mysql
    security_opt:
      - seccomp:unconfined
    restart: always
    networks: 
      - my-net
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 10087:3306

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/xylink/redis:3.2_v1
    container_name: redis
    restart: always
    networks:
      - my-net
    ports:
      - 9999:6379
    volumes:
      - $PWD/redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    networks:
        - my-net
    ports:
      - "9899:80"
    volumes:
      - $PWD/nginx/Client:/usr/share/nginx/html # 把我们的前端页面映射到/usr/share/nginx/html,这样nginx就会执行我们的前端页面
      - $PWD/nginx/conf.d:/etc/nginx/conf.d # 把我们要配置的nginx文件映射到/etc/nginx/conf.d,这样nginx就会执行我们的配置
