version:
    "3.1"
networks:
    my-net:
services:
  golang:
    build: ./go
    container_name: golang
    restart: always
    networks:
      - my-net  
    ports:
      - "10085:8080"
    volumes:
      - ./conf/go:/root/conf
    depends_on:
      - mysql

  grafana:
    image: grafana/grafana
    container_name: grafana2
    restart: always
    networks:
      - my-net
    ports:
      - 10086:3000

  mysql:
    image: mysql
    container_name: mysql
    security_opt:
      - seccomp:unconfined
    restart: always
    networks: 
      - my-net
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 10087:3306
